# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-18 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_events_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Events'),
        ),
    ]
