# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20160618_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='good',
            field=models.BooleanField(default=True),
        ),
    ]
