# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20160619_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='pincode',
            field=models.CharField(default='dadsa', max_length=6),
            preserve_default=False,
        ),
    ]
